version: "3.6"
services:
    proxy:
        build:
            context: .
            dockerfile: Dockerfile.proxy
        ports:
            - "80:80"
            - "443:443"
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
