version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
      corelib:
        patterns:
          - "LeanCode.*"
      mass-transit:
        patterns:
          - "MassTransit.*"
      open-telemetry:
        patterns:
          - "OpenTelemetry.*"
      npgsql:
        patterns:
          - "Npgsql.*"
      other:
        patterns:
          - "*"
        exclude-patterns:
          - "Microsoft.*"
          - "LeanCode.*"
          - "MassTransit.*"
          - "OpenTelemetry.*"
          - "Npgsql.*"