version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
      other:
        patterns:
          - "*"
        exclude-patterns:
          - "Microsoft.*"