version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
      corelib:
        patterns:
          - "LeanCode.*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      mass-transit:
        patterns:
          - "MassTransit"
          - "MassTransit.*"
      open-telemetry:
        patterns:
          - "OpenTelemetry"
          - "OpenTelemetry.*"
      npgsql:
        patterns:
          - "Npgsql"
          - "Npgsql.*"
      other:
        patterns:
          - "*"
        exclude-patterns:
          - "Microsoft.*"
          - "LeanCode.*"
          - "MassTransit"
          - "MassTransit.*"
          - "OpenTelemetry"
          - "OpenTelemetry.*"
          - "Npgsql"
          - "Npgsql.*"