apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: exampleapp
image: docker.io/rancher/k3s:v1.31.0-k3s1
# image: leancode.azurecr.io/rancher/k3s:v1.31.0-k3s1-fuseoverlayfs
# Check apps/Dockerfile.k3s to see how to build this image
servers: 1
agents: 0
kubeAPI:
  host: "exampleapp-cluster.local.lncd.pl"
  hostIP: "127.0.0.1"
  hostPort: "6445"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 1433:1433
    nodeFilters:
      - loadbalancer
  - port: 5432:5432
    nodeFilters:
      - loadbalancer
  - port: 10000:10000
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: k3d-exampleapp-registry.local.lncd.pl
    host: "0.0.0.0"
    hostPort: "21345"
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --kubelet-arg=eviction-hard=imagefs.available<5Gi,nodefs.available<2Gi,memory.available<1Gi
        nodeFilters:
          - all
      # - arg: --snapshotter=fuse-overlayfs
      #   nodeFilters:
      #     - all
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
