FROM mcr.microsoft.com/dotnet/aspnet:8.0

USER $APP_UID

WORKDIR /home/app

EXPOSE 8080

ENV ASPNETCORE_FORWARDEDHEADERS_ENABLED=true

COPY src/Examples/ExampleApp.Examples/deploy .

ENTRYPOINT ["dotnet", "ExampleApp.Examples.dll"]
