FROM mcr.microsoft.com/dotnet/aspnet:8.0

USER $APP_UID

WORKDIR /home/app

COPY src/Examples/ExampleApp.Examples.Migrations/deploy .

ENTRYPOINT ["dotnet", "ExampleApp.Examples.Migrations.dll", "migrate"]
