apiVersion: batch/v1
kind: Job
metadata:
  name: exampleapp-examples-migrations
  namespace: exampleapp-dev
  labels:
    app: exampleapp-examples-migrations
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: exampleapp-examples-migrations
    spec:
      containers:
      - name: migrations
        image: exampleapp-examples-migrations
        resources:
          requests:
            cpu: '500m'
            memory: '200Mi'
          limits:
            cpu: '1'
            memory: '1Gi'
      restartPolicy: OnFailure
