FROM mcr.microsoft.com/dotnet/aspnet:8.0

USER $APP_UID

ARG APP_VERSION

ENV APP_VERSION=${APP_VERSION}
ENV ASPNETCORE_ENVIRONMENT=Development

COPY --chown=$APP_UID config /home/app/config
COPY --chown=$APP_UID out/migrations /home/app/bin/migrations

WORKDIR /home/app/bin
ENTRYPOINT ["/bin/bash", "-c", "source /home/app/config/config.sh && ./migrations"]
