FROM leancode.azurecr.io/locallncdpl-certs AS certs

FROM traefik

COPY --from=certs /certs/local.lncd.pl.cert /certs/local.lncd.pl.cert
COPY --from=certs /certs/local.lncd.pl.key /certs/local.lncd.pl.key
COPY dynamic.toml /config/dynamic/main.toml
