FROM bitnami/rabbitmq:3.12.6

USER root
RUN curl -LO --output-dir /opt/bitnami/rabbitmq/plugins https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez
USER 1001

RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange rabbitmq_management
