[http]
  [http.routers]
    [http.routers.local]
      entryPoints = ["web", "websecure"]
      service = "local"
      rule = "Host(`local.lncd.pl`)"
      priority = 99
      [http.routers.local.tls]
[http.services]
  [http.services.local.loadBalancer]
    [[http.services.local.loadBalancer.servers]]
      url = "http://host.k3d.internal:4200/"

[http.middlewares]
  [http.middlewares.redirecthttps.redirectScheme]
    scheme = "https"

[[tls.certificates]]
  certFile = "/certs/local.lncd.pl.cert"
  keyFile = "/certs/local.lncd.pl.key"
  stores = ["default"]
